### ISSUE TITLE
dia critic

### ISSUE THREAD

**Issue by mi2ebi** [selaere/selaere.github.io#1]
there's also diacritics in `U+20D0..20FF` ([here](https://www.unicode.org/charts/PDF/U20D0.pdf))

and they're going to add 15 more in september ([these](https://www.unicode.org/charts/PDF/Unicode-14.0/U140-1AB0.pdf) and [this other one](https://www.unicode.org/charts/PDF/Unicode-14.0/U140-1DC0.pdf))

also yes this is ccj merrybot

**Comment by selaere** [comment]
yes i removed them literally zero fonts support them

**Comment by mi2ebi** [comment]
noto sans symbols 2 does iirc

**Comment by selaere** [comment]
sorry i uhh didnt know that existed

i've added those few to [diacritic](http://selaere.github.io/diacritic), and i've made a new page, [diacritic-full](http://selaere.github.io/diacritic-full), that contains every single `Mn` character in unicode, for completeness. it's 143 KB 😳

i'll add the unicode 14 ones when the update releases it's a bit pointless now
